apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: helm-opendatahub
  namespace: {{  .Values.namespace }}
  finalizers:
    - kfdef-finalizer.kfdef.apps.kubeflow.org
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odhseldon/cluster
      name: odhseldon
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: openshift-operators
        repoRef:
          name: manifests
          path: kafka/cluster
      name: strimzi-operator
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: kafka/kafka
      name: kafka-cluster

    - kustomizeConfig:
        parameters:
          - name: SUPERSET_ADMIN_PASSWORD
            value: admin
        repoRef:
          name: manifests
          path: superset
      name: superset
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: radanalyticsio/spark/cluster
      name: radanalyticsio-spark-cluster
    - kustomizeConfig:
        parameters:
          - name: s3_endpoint_url
            value: s3.odh.com
        repoRef:
          name: manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          - additional
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: airflow/operator
      name: airflow-operator
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
  repos:
    - name: kf-manifests
      uri: 'https://github.com/kubeflow/manifests/tarball/v1.2-branch'
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.0.0'